emrapp/emrapp/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
# from django.contrib.auth.views import password_reset
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from emrapp import views
urlpatterns = patterns(
    '',
    # Examples:
    # url(r'^$', 'emrapp.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    # points to base index page (emrapp/views.py etc.)
    url(r'^$', views.login_page, {'success_msg' : None},
        name='login'),
    # built in admin page
    url(r'^admin/', include(admin.site.urls)),
    # additional app pages go here (ie: patient app etc)
    url(r'^patient/', include('patient.urls', namespace='patient')),
    url(r'^logout/', views.logout_page, name='logout'),
    url(r'^success/$', views.login_page, {'success_msg' : 'Instructions sent to your inbox.'},
        name='password_change_sent'),
    url(r'^reset/login/$', views.login_page, {'success_msg' : 'Password reset, you may now login.'},
        name='password_reset_complete'),

    url(r'^reset/$',
        'django.contrib.auth.views.password_reset',
        {'post_reset_redirect' : '/success'},
        name="password_reset"),
    url(r'^password/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',
        'django.contrib.auth.views.password_reset_confirm',
        name='password_reset_confirm'),


) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

emrapp/patient/urls.py
from django.conf.urls import patterns, url

from patient import views

urlpatterns = patterns('',
#    url(r'^$', views.index, name='index'),

    # /patient/patient_id/
    url(r'^(?P<patient_id>\d+)/$', views.dashboard, name='dashboard'), # after the patient logs in, you do not need to build this view yet

    # /patient/patient_id/vitals/
    url(r'^(?P<patient_id>\d+)/vitals/$', views.vitals, name='vitals'), # this calls the views.vitals() function when this link is requested

    # /patient/patient_id/allergies/
    url(r'^(?P<patient_id>\d+)/allergies/$', views.allergies, name='allergies'), # this calls the views.allergies() function when this link is requested

    # /patient/patient_id/medication/
    url(r'^(?P<patient_id>\d+)/medication/$', views.medication, name='medication'), # this calls the views.medication() function when this link is requested

    # /patient/patient_id/insurance/
    url(r'^(?P<patient_id>\d+)/insurance/$', views.insurance, name='insurance'), # this calls the views.insurance() function when this link is requested

    # /patient/patient_id/conditions/
    url(r'^(?P<patient_id>\d+)/medicalHistory/$', views.medicalHistory, name='medicalHistory'), # this calls the views.conditions() function when this link is requested

    # /patient/patient_id/diagnosticresults/
    url(r'^(?P<patient_id>\d+)/diagnosticresults/$', views.diagnosticresults, name='diagnosticresults'), # this calls the views.labresults() function when this link is requested

    # /patient/patient_id/appts/
    url(r'^(?P<patient_id>\d+)/appts/$', views.appts, name='appts'), # this calls the views.appts() function when this link is requested

     # /patient/patient_id/settings/
    url(r'^(?P<patient_id>\d+)/settings/$', views.settings, name='settings'), # this calls the views.settings() function when this link is requested

)

emrapp/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}

{% block meta %}
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
{% endblock %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.min.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap-theme.min.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/style-override.css' %}" />
{% endblock %}

{% block title %}
<TITLE>{{ page_name }}</TITLE>
{% endblock %}

{% block nav %}
<div class="header">
  <div class="container">
    <nav class="navbar navbar-default" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          {% block nav-home %}<a class="navbar-brand" href="{% url 'patient:dashboard' patient.id %}">EMR</a>{% endblock %}
        </div>
        <div class="collapse navbar-collapse" id="main-navbar-collapse">
          <ul class="nav navbar-nav">
            <li{% block nav-vitals %}{% endblock %}><a href="{% url 'patient:vitals' patient.id %}">Vitals</a></li>
            <li{% block nav-allergies %}{% endblock %}><a href="{% url 'patient:allergies' patient.id %}">Allergies</a></li>
            <li{% block nav-medication %}{% endblock %}><a href="{% url 'patient:medication' patient.id %}">Medication</a></li>
            <li{% block nav-insurance %}{% endblock %}><a href="{% url 'patient:insurance' patient.id %}">Insurance</a></li>
            <li{% block nav-medicalHistory %}{% endblock %}><a href="{% url 'patient:medicalHistory' patient.id %}">Medical History</a></li>
            <li{% block nav-labresults %}{% endblock %}><a href="{% url 'patient:diagnosticresults' patient.id %}">Diagnostic Results</a></li>
            <li{% block nav-appts %}{% endblock %}><a href="{% url 'patient:appts' patient.id %}">Appointments</a></li>

            <!--

             -->

          </ul>
          <p class="navbar-text navbar-right">
            Signed in as <a href="{% url 'patient:dashboard' patient.id %}" class="navbar-link">{{ patient.first_name }} {{ patient.last_name }}</a>&nbsp;|&nbsp;
            <a href="{% url 'patient:settings' patient.id %}" class="navbar-link">Settings</a>&nbsp;|&nbsp;
            <a href="{% url 'logout' %}" class="navbar-link">Logout</a>
          </p>
        </div>
      </div> <!--/.navbar-collapse-->
    </nav> <!--/.navbar-->
  </div> <!--/.container-->
</div> <!--/.header-->
{% endblock %}

{% block content%}
<div class="container">
  <div class="well well-lg clearfix">
      <div class="col-md-12 col-lg-12">
        <h1>{{ page_name }}</h1>
      </div> <!-- end header bootstrap row -->
    <div class="col-md-4 col-lg-4">
        {% block content-loop %}
            {% if data %}
                {% for i in data %}
                    {% block content-data %}
                    <!-- each page fills in their own data to be displayed -->
                    {% endblock %}
                {% endfor %}
            {% else %}
                <p>You currently have no {{ page_name|lower }} on file.</p>
            {% endif %}
        {% endblock %}
    </div> <!-- data column -->
    <div class="col-md-4 col-lg-4 hidden-xs hidden-sm">
    </div><!-- empty column -->

    <div class="col-md-4 col-lg-4 hidden-xs hidden-sm">
    {% block content-picture %}
      <img class='img-responsive' src='' alt="img goes here"/>
    {% endblock %}
    </div><!-- picture column -->
  </div>
</div>



{% endblock %}

{% comment %}
<noscript>
    <style type="text/css">#forNoScript {display:none;}</style>
    <div class="container">
        <div class="row clearfix">
            <div class="col-md-6 col-md-offset-3">
                <div class="alert alert-warning marginTop30">
                    Javascript must be enabled to use this website.
                </div>
            </div>
        </div>
    </div>
</noscript>
{% endcomment %}

{% block footer %}
<div class="footer">
  <div class="container">
    <div class="col-md-12 col-lg-12">
      <div class="text-muted text-center">
        <p>&copy; 2014 - Chris Coe, Robert Duncan, Latisha Swann, Mike Williams</p>
        <p>All credit for images go to their respective owners</p>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% include 'main/footer.html' %}

emrapp/templates/main/footer.html
{% load staticfiles %}

{% block scripts %}
<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
<!-- Google Analytics -->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-55213503-1', 'auto');
  ga('send', 'pageview');

</script>
<!-- END Google Analytics -->
<!-- Google Tag Manager -->
<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-M36FVV"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-M36FVV');</script>
<!-- End Google Tag Manager -->
{% endblock %}