emrapp/emrapp/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
# from django.contrib.auth.views import password_reset
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from emrapp import views
urlpatterns = patterns(
    '',
    # Examples:
    # url(r'^$', 'emrapp.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    # points to base index page (emrapp/views.py etc.)
    url(r'^$', views.login_page, {'success_msg' : None},
        name='login'),
    # built in admin page
    url(r'^admin/', include(admin.site.urls)),
    # additional app pages go here (ie: patient app etc)
    url(r'^patient/', include('patient.urls', namespace='patient')),
    url(r'^logout/', views.logout_page, name='logout'),
    url(r'^success/$', views.login_page, {'success_msg' : 'Instructions sent to your inbox.'},
        name='password_change_sent'),
    url(r'^reset/login/$', views.login_page, {'success_msg' : 'Password reset, you may now login.'},
        name='password_reset_complete'),

    url(r'^reset/$',
        'django.contrib.auth.views.password_reset',
        {'post_reset_redirect' : '/success'},
        name="password_reset"),
    url(r'^password/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',
        'django.contrib.auth.views.password_reset_confirm',
        name='password_reset_confirm'),


) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

emrapp/patient/urls.py
from django.conf.urls import patterns, url

from patient import views

urlpatterns = patterns('',
#    url(r'^$', views.index, name='index'),

    # /patient/patient_id/
    url(r'^(?P<patient_id>\d+)/$', views.dashboard, name='dashboard'), # after the patient logs in, you do not need to build this view yet

    # /patient/patient_id/vitals/
    url(r'^(?P<patient_id>\d+)/vitals/$', views.vitals, name='vitals'), # this calls the views.vitals() function when this link is requested

    # /patient/patient_id/allergies/
    url(r'^(?P<patient_id>\d+)/allergies/$', views.allergies, name='allergies'), # this calls the views.allergies() function when this link is requested

    # /patient/patient_id/medication/
    url(r'^(?P<patient_id>\d+)/medication/$', views.medication, name='medication'), # this calls the views.medication() function when this link is requested

    # /patient/patient_id/insurance/
    url(r'^(?P<patient_id>\d+)/insurance/$', views.insurance, name='insurance'), # this calls the views.insurance() function when this link is requested

    # /patient/patient_id/conditions/
    url(r'^(?P<patient_id>\d+)/medicalHistory/$', views.medicalHistory, name='medicalHistory'), # this calls the views.conditions() function when this link is requested

    # /patient/patient_id/diagnosticresults/
    url(r'^(?P<patient_id>\d+)/diagnosticresults/$', views.diagnosticresults, name='diagnosticresults'), # this calls the views.labresults() function when this link is requested

    # /patient/patient_id/appts/
    url(r'^(?P<patient_id>\d+)/appts/$', views.appts, name='appts'), # this calls the views.appts() function when this link is requested

     # /patient/patient_id/settings/
    url(r'^(?P<patient_id>\d+)/settings/$', views.settings, name='settings'), # this calls the views.settings() function when this link is requested

)

emrapp/patient/models.py
from django.conf import settings
from django.core.validators import RegexValidator, MaxValueValidator
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)
from django.db import models


class PatientManager(BaseUserManager):

    def create_user(self, email,
                    #                     first_name, last_name,
                    password=None):
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=PatientManager.normalize_email(email),
            #             first_name=first_name,
            #             last_name=last_name,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(
            self, email,
        #             first_name, last_name,
            password):
        user = self.create_user(
            email=email,
            #             first_name=first_name,
            #             last_name=last_name,
            password=password,
        )
        user.is_admin = True
        user.is_staff = True
        user.save(using=self._db)
        return user

AlphaValidator = RegexValidator(
    r'^[a-z :A-Z]*$', 'Only letter characters are allowed.')
AlphanumericValidator = RegexValidator(
    r'^[0-9 a-z:A-Z]*$', 'Only alphanumeric characters are allowed.')


class Patient(AbstractBaseUser):
    # http://stackoverflow.com/questions/11351619/
    #     how-to-make-djangos-datetimefield-optional

    STATE_CHOICES = (
        ('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'),
        ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'),
        ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'),
        ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'),
        ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'),
        ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'),
        ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'),
        ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'),
        ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'),
        ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'),
        ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'),
        ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'),
        ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'),
        ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'),
        ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'),
        ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'),
        ('WY', 'Wyoming'),
    )

    email = models.EmailField(max_length=254, unique=True, db_index=True)
    first_name = models.CharField(
        ('First Name'), max_length=30, blank=True, null=True,
        validators=[AlphaValidator])
    last_name = models.CharField(
        ('Last Name'), max_length=30, blank=True, null=True,
        validators=[AlphaValidator])
    phone_num = models.CharField(max_length=12, blank=True, null=True)
    street_address = models.CharField(max_length=255, blank=True, null=True)
    city = models.CharField(
        max_length=255, blank=True, null=True, validators=[AlphaValidator])
    state = models.CharField(
        max_length=255, blank=True, null=True, choices=STATE_CHOICES
    )
    zip_code = models.IntegerField(
        blank=True, null=True, validators=[MaxValueValidator(99999)])
    date_of_birth = models.DateField(blank=True, null=True)
    ssn = models.IntegerField(
        blank=True, null=True, validators=[MaxValueValidator(999999999)])

    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)

    objects = PatientManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELD = []

    def get_full_name(self):
        return self.email
#         return '{} {}'.format(Patient.first_name, Patient.last_name)

    def get_short_name(self):
        return self.email
#         return Patient.first_name

    def __unicode__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True


class Allergy(models.Model):

    SEVERITY_CHOICES = (
        ('1', 'Mild'),
        ('2', 'Mild - Moderate'),
        ('3', 'Moderate'),
        ('4', 'Moderate - Severe'),
        ('5', 'Severe'),
    )

    id_patient = models.ForeignKey(settings.AUTH_USER_MODEL)
    allergy_name = models.CharField(
        max_length=255, null=True, validators=[AlphaValidator])
    severity = models.CharField(
        max_length=255, validators=[AlphanumericValidator],
        choices=SEVERITY_CHOICES
    )
    allergy_description = models.CharField(
        max_length=255, validators=[AlphanumericValidator])
    allergy_date = models.DateField('Date of allergy diagnosis')
    allergy_notes = models.CharField(max_length=255, blank=True)

    def __unicode__(self):
        return self.allergy_name

    class Meta:
        verbose_name = 'Allergy'
        verbose_name_plural = 'Allergies'
        ordering = ['-allergy_date']


class Appointment(models.Model):

    TYPE_CHOICES = (
        ('OV', 'Office Visit'),
        ('CPX', 'Annual Physical'),
        ('WC', 'Well Child'),
        ('NV', 'Nurse Visit'),
        ('AI', 'Allergy Injection'),
        ('PAT', 'Pre-Admission Testing'),
        ('PAP', 'PAP'),
        ('BLDWK', 'Blood Work'),
        ('FU', 'Hospital Followup'),
        ('DEXA', 'Bone Density Scan'),
        ('NP', 'New Patient'),
    )

    id_patient = models.ForeignKey(settings.AUTH_USER_MODEL)
    appointment_type = models.CharField(
        max_length=255, null=True, choices=TYPE_CHOICES
    )
    appointment_description = models.CharField(max_length=255, null=True)
    appointment_date = models.DateField('Date of appointment')
    appointment_notes = models.CharField(max_length=255, null=True, blank=True)

    def __unicode__(self):
        return self.appointment_type

    class Meta:
        ordering = ['-appointment_date']


class InsurancePolicy(models.Model):
    id_patient = models.ForeignKey(settings.AUTH_USER_MODEL)
    policy_num = models.CharField(
        max_length=255, validators=[AlphanumericValidator])
    comp_name = models.CharField('Company Name',
                                 max_length=255, validators=[AlphanumericValidator])
    group_num = models.CharField(
        max_length=255, validators=[AlphanumericValidator])
    exp_date = models.DateField('expiration date')

    def __unicode__(self):
        return self.policy_num

    class Meta:
        verbose_name = 'Insurance Policy'
        verbose_name_plural = 'Insurance Policies'
        ordering = ['-exp_date']


class DiagnosticResult(models.Model):
    id_patient = models.ForeignKey(settings.AUTH_USER_MODEL)
    result_title = models.CharField(max_length=255)
    result_description = models.CharField(max_length=255)
    result_date = models.DateField('date of result')
    result_notes = models.CharField(max_length=255, null=True, blank=True)

    def __unicode__(self):
        return self.result_title

    class Meta:
        ordering = ['-result_date']


class MedicalHistory(models.Model):
    id_patient = models.ForeignKey(settings.AUTH_USER_MODEL)
    history_item_name = models.CharField(max_length=255)
    is_family_item = models.BooleanField(default=False)
    history_description = models.CharField(max_length=255)
    history_item_date = models.DateField('Diagnosis date of History Item')
    history_notes = models.CharField(max_length=255, null=True, blank=True)

    def __unicode__(self):
        return self.history_item_name

    class Meta:
        verbose_name = 'Medical History'
        verbose_name_plural = 'Medical History'
        ordering = ['-history_item_date']


class Medication(models.Model):
    id_patient = models.ForeignKey(settings.AUTH_USER_MODEL)
    medication_name = models.CharField(max_length=255)
    dosage = models.CharField(max_length=255)
    medication_description = models.CharField(
        max_length=255, null=True, blank=True)
    medication_date = models.DateField('Date of Perscription')
    medication_notes = models.CharField(max_length=255, null=True, blank=True)

    def __unicode__(self):
        return self.medication_description

    class Meta:
        ordering = ['-medication_date']


class Vital(models.Model):
    id_patient = models.ForeignKey(settings.AUTH_USER_MODEL)
    height_inches = models.DecimalField(
        max_digits=4, decimal_places=2, null=True, blank=True)
    weight_pounds = models.DecimalField(
        max_digits=5, decimal_places=2, null=True, blank=True)
    bp_sys = models.IntegerField(null=True, blank=True)
    bp_dias = models.IntegerField(null=True, blank=True)
    pulse = models.IntegerField(null=True, blank=True)
    vitals_date = models.DateField('vitals date', null=True, blank=True)
    vitals_notes = models.CharField(max_length=255, null=True, blank=True)

    def __unicode__(self):
        return unicode(self.pulse)

    class Meta:
        ordering = ['-vitals_date']

emrapp/patient/forms.py
'''
Created on Nov 25, 2014

@author: chrcoe
'''
from django import forms
from patient.models import Patient


class SettingsForm(forms.Form):

    '''
    Basic Django form class to allow displaying dropdown list of all state
    choices for Settings page on Patient site.
    '''

    CUSTOM_ATTRIB = {'class': 'form-control'}

    state = forms.ChoiceField(
        choices=Patient.STATE_CHOICES,
        widget=forms.Select(attrs=CUSTOM_ATTRIB)
    )

emrapp/patient/templates/patient/allergies.html
{% extends 'main/base.html' %}
{% load staticfiles %}
{% block nav-allergies %} class="active"{% endblock %}

{% block content-data %}
<h3>{{ i.allergy_name }}</h3>
<ul>
    <li><b>Severity:</b> {{ i.get_severity_display }}
    <li><b>Allergy description:</b> {{ i.allergy_description }}
    <li><b>Allergy Date:</b> {{ i.allergy_date }}
    <p>Patient notes: {{ i.allergy_notes }}
</ul>
<form class="form-horizontal" role="form" action="{% url 'patient:allergies' patient.id %}" method='post'>
      {% csrf_token %}
      <div class="form-group">
        <textarea class="form-control" name="allergy_notes" placeholder="enter new notes here" textarea></textarea>
        <input type="hidden" name="allergies_id" value='{{ i.id }}' />
      </div>
      <div class="form-group">
          <button type="submit" class="btn btn-primary">Submit</button>
       </div>
</form>
{% endblock %}
{% block content-picture %}
  <img class='img-responsive img-rounded' src='{% static 'img/allergies-3.jpg' %}' />
{% endblock %}

emrapp/patient/templates/patient/appts.html
{% extends 'main/base.html' %}
{% load staticfiles %}
{% block nav-appts %} class="active"{% endblock %}

{% block content-data %}
<h3>{{ i.get_appointment_type_display }}</h3>
<ul>
    <li><b>Date:</b> {{ i.appointment_date }}
    <li><b>Description:</b> {{ i.appointment_description }}
    <li>Patient notes: {{ i.appointment_notes }}
</ul>
<form class="form-horizontal" role="form" action="{% url 'patient:appts' patient.id %}" method='post'>
      {% csrf_token %}
      <div class="form-group">
        <textarea class="form-control" name="appts_notes" placeholder="enter new notes here" textarea></textarea>
        <input type="hidden" name="appts_id" value='{{ i.id }}' />
      </div>
      <div class="form-group">
          <button type="submit" class="btn btn-primary">Submit</button>
       </div>
</form>
{% endblock %}
{% block content-picture %}
  <img class='img-responsive img-rounded' src='{% static 'img/appts-1.jpg' %}' />
{% endblock %}

emrapp/patient/templates/patient/diagnosticresults.html
{% extends 'main/base.html' %}
{% load staticfiles %}
{% block nav-labresults %} class="active"{% endblock %}

{% block content-data %}
<h3>{{ i.result_title }}</h3>
<ul>
    <li><b>Description:</b> {{ i.result_description }}
    <li><b>Date of Results:</b> {{ i.result_date }}
    <p>Patient notes: {{ i.result_notes }}
</ul>
<form class="form-horizontal" role="form" action="{% url 'patient:diagnosticresults' patient.id %}" method='post'>
      {% csrf_token %}
      <div class="form-group">
        <textarea class="form-control" name="result_notes" placeholder="enter new notes here" textarea></textarea>
        <input type="hidden" name="result_id" value='{{ i.id }}' />
      </div>
      <div class="form-group">
          <button type="submit" class="btn btn-primary">Submit</button>
      </div>
</form>
{% endblock %}
{% block content-picture %}
  <img class='img-responsive img-rounded' src='{% static 'img/results-1.jpg' %}' />
{% endblock %}


emrapp/patient/templates/patient/insurance.html
{% extends 'main/base.html' %}
{% load staticfiles %}
{% block nav-insurance %} class="active"{% endblock %}

{% block content-data %}
<h3>{{ i.comp_name }}</h3>
<ul>
    <li><b>Policy Number:</b> {{ i.policy_num }}
    <li><b>Group Number:</b> {{ i.group_num }}
    <li><b>Expiration Date:</b> {{ i.exp_date }}
</ul>
{% endblock %}

{% block content-picture %}
  <img class='img-responsive img-rounded' src='{% static 'img/insurance-2.jpg' %}' />
{% endblock %}

emrapp/patient/templates/patient/medicalHistory.html
{% extends 'main/base.html' %}
{% load staticfiles %}
{% block nav-medicalHistory %} class="active"{% endblock %}

{% block content-data %}
<h3>{{ i.history_item_name }}</h3>
<ul>
    <li><b>Is there a family history of condition:</b> {{ i.is_family_item }}
    <li><b>Description of history:</b> {{ i.history_description }}
    <li><b>Date history was diagnosed:</b> {{ i.history_item_date }}
    <p>Patient notes: {{ i.history_notes }}
</ul>
<form class="form-horizontal" role="form" action="{% url 'patient:medicalHistory' patient.id %}" method='post'>
      {% csrf_token %}
      <div class="form-group">
        <textarea class="form-control" name="history_notes" placeholder="enter new notes here" textarea></textarea>
        <input type="hidden" name="history_id" value='{{ i.id }}' />
      </div>
      <div class="form-group">
          <button type="submit" class="btn btn-primary">Submit</button>
      </div>
</form>
{% endblock %}
{% block content-picture %}
  <img class='img-responsive img-rounded' src='{% static 'img/history-1.jpg' %}' />
{% endblock %}

emrapp/patient/templates/patient/medication.html
{% extends 'main/base.html' %}
{% load staticfiles %}
{% block nav-medication %} class="active"{% endblock %}

{% block content-data %}
<h3>{{ i.medication_name }}</h3>
<ul>
    <li><b>Dosage:</b> {{ i.dosage }}
    <li><b>Description:</b> {{ i.medication_description }}
    <li><b>Date Perscribed:</b> {{ i.medication_date }}
    <p>Patient notes: {{ i.medication_notes }}</p>
</ul>
<form class="form-horizontal" role="form" action="{% url 'patient:medication' patient.id %}" method='post'>
  {% csrf_token %}
  <div class="form-group">
    <textarea class="form-control" name="medication_notes" placeholder="enter new notes here" textarea></textarea>
    <input type="hidden" name="medication_id" value='{{ i.id }}' />
  </div>
  <div class="form-group">
    <button type="submit" class="btn btn-primary">Submit</button>
  </div>
</form>
{% endblock %}
{% block content-picture %}
  <img class='img-responsive img-rounded' src='{% static 'img/meds-3.jpg' %}' />
{% endblock %}

emrapp/patient/templates/patient/password_change_done.html
{% extends 'main/base.html' %}

<h1>{{ title }}</h1>

{% block nav %}{% endblock %}

{% block content %}
<div class="header">
  <div class="container">
    <p>Your password was changed.</p>
    Click <a href="{% url 'logout' %}">here</a> to login.
  </div>
</div>
{% endblock %}

emrapp/patient/templates/patient/password_change_form.html
{% extends 'main/base.html' %}

<h1>{{ title }}</h1>

{% block nav %}{% endblock %}

{% block content %}
<div class="header">
  <div class="container">
    <form action="" method="post">{% csrf_token %}
      <div>
      {% if form.errors %}
          <p class="errornote">
          {% if form.errors.items|length == 1 %}
            Please correct the error below.
          {% else %}
            Please correct the errors below.
          {% endif %}
          </p>
      {% endif %}

        <br />
        <br />
        <br />


        <fieldset class="module aligned wide">

        <div class="form-row">
            {{ form.old_password.errors }}
            {{ form.old_password.label_tag }} {{ form.old_password }}
        </div>

        <div class="form-row">
            {{ form.new_password1.errors }}
            {{ form.new_password1.label_tag }} {{ form.new_password1 }}
        </div>

        <div class="form-row">
        {{ form.new_password2.errors }}
            {{ form.new_password2.label_tag }} {{ form.new_password2 }}
        </div>

        </fieldset>

      <div class="submit-row">
          <input type="submit" value="Change my password" class="default" />
      </div>

      <script type="text/javascript">document.getElementById("id_old_password").focus();</script>
      </div>
    </form>
  </div>
</div>

{% endblock %}

emrapp/patient/templates/patient/settings.html
{% extends 'main/base.html' %}
{% block nav-settings %} class="active"{% endblock %}

{% block content %}
<script type='text/javascript'>
function validateForm() {
    var x = document.forms["settingsForm"]["phone_num"].value;
    var temp_num = x.replace(/-/g, '');
    if (temp_num==null || temp_num=="" || temp_num.length!==10 || /\D/.test(temp_num)) {
        alert("Phone number must be in this format: 555-555-5555.");
        return false;
    }

    x = document.forms["settingsForm"]["street_address"].value;
    if (x==null || x=="") {
        alert("Street address must not be empty.");
        return false;
    }

    x = document.forms["settingsForm"]["city"].value;
    if (x==null || x=="" || /^[a-zA-Z]*$/.test(x)==false) {
        alert("City must be all alphabet characters.");
        return false;
    }

    x = document.forms["settingsForm"]["zip_code"].value;
    if (x==null || x.length!==5 || /\D/.test(x)) {
        alert("Zip code must be 5 numbers.");
        return false;
    }
}
</script>
<div class="container">
  <div class="well well-lg clearfix">
      <div class="col-md-12 col-lg-12">
        <h1><p class="text-center">{{ page_name }}</p></h1>
      </div>
    <div class="col-md-4 col-lg-4">
      {% if errMsg %}
        <div class="alert alert-danger alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          {{ errMsg }}
        </div>
      {% endif %}
      {% if successMsg %}
        <div class="alert alert-success alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          {{ successMsg }}
        </div>
      {% endif %}
      <form name="settingsForm" class="form-horizontal" role="form" action="{% url 'patient:settings' patient.id %}" onsubmit="return validateForm();" method='post'>
        {% csrf_token %}
        <div class="form-group">
          <label class="control-label" for="id_phone">Phone Number (ex. 555-555-5555 or 5555555555):</label>
          <textarea id="id_phone" class="form-control" name="phone_num" style="resize:none">{{ patient.phone_num }}</textarea>
        </div>
        <div class="form-group">
          <label class="control-label" for="id_street">Street Address:</label>
          <textarea id="id_street" class="form-control" name="street_address" style="resize:none">{{ patient.street_address}}</textarea>
        </div>
        <div class="form-group">
          <label class="control-label" for="id_city">City:</label>
          <textarea id="id_city" class="form-control" name="city" style="resize:none">{{ patient.city }}</textarea>
        </div>
        <!-- Select Basic -->
        <div class="form-group">
          <label class="control-label" for="id_state">State:</label>
          {{ settings_form.state }}
        </div>
        <div class="form-group">
          <label class="control-label" for="id_zip">Zip Code (ex. 55555):</label>
          <textarea id="id_zip" class="form-control" name="zip_code" style="resize:none">{{ patient.zip_code }}</textarea>
        </div>
        <input type="hidden" name="patient_id" value='{{ patient.id }}' />
        <input type="hidden" name="is_changing_demographics" value="True">
        <div class="form-group">
          <button type="submit" class="btn btn-primary">Submit</button>
        </div>
      </form>
    </div>
    <div class="col-md-4 col-lg-4">
    <!-- hidden div for spacing -->
    </div>
    <div class="col-md-4 col-lg-4">
      <form class="form-horizontal" role="form" action="" method='post'>
      {% csrf_token %}
        {% if pw_form.errors %}
            <div class="alert alert-danger alert-dismissible" role="alert">
              <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
            {% if pw_form.errors.items|length == 1 %}
              Please correct the error below.
            {% else %}
              Please correct the errors below.
            {% endif %}
            </div>
        {% endif %}
        {% if pwSuccessMsg %}
          <div class="alert alert-success alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
            {{ pwSuccessMsg }}
          </div>
        {% endif %}
          <div class="form-group">
              {{ pw_form.old_password.errors }}
              <input type="password" class="form-control" name="old_password" placeholder="Current Password" value="" />
          </div>
          <div class="form-group">
              {{ pw_form.new_password1.errors }}
              <input type="password" class="form-control" name="new_password1" placeholder="New Password" value="" />
          </div>
          <div class="form-group">
              {{ pw_form.new_password2.errors }}
              <input type="password" class="form-control" name="new_password2" placeholder="Confirm New Password" value="" />
          </div>
          <input type="hidden" name="is_changing_password" value="True">
          <div class="form-group">
              <button type="submit" class="btn btn-primary">Change my password</button>
          </div>
        <script type="text/javascript">document.getElementById("id_old_password").focus();</script>
      </form>
    </div>
    </div>
  </div>
</div>
{% endblock %}

emrapp/patient/templates/patient/vitals.html
{% extends 'main/base.html' %}
{% load staticfiles %}
{% block nav-vitals %} class="active"{% endblock %}

{% block content-data %}
<h3>{{ i.vitals_date }}</h3>
<ul>
    <li><b>Height:</b> {{ i.height_inches }} inches
    <li><b>Weight:</b> {{ i.weight_pounds }} pounds
    <li><b>Blood Pressure:</b> {{ i.bp_sys }}/{{ i.bp_dias }}
    <li><b>Pulse:</b> {{ i.pulse }} beats per minute - A resting pulse of 60 to 80 is ideal.
    <p>Patient notes: {{ i.vitals_notes }}
</ul>
<form class="form-horizontal" role="form" action="{% url 'patient:vitals' patient.id %}" method='post'>
      {% csrf_token %}
      <div class="form-group">
        <textarea class="form-control" name="vitals_notes" placeholder="enter new notes here" textarea></textarea>
        <input type="hidden" name="vitals_id" value='{{ i.id }}' />
      </div>
      <div class="form-group">
          <button type="submit" class="btn btn-primary">Submit</button>
      </div>
</form>
{% endblock %}
{% block content-picture %}
  <img class='img-responsive img-rounded' src='{% static 'img/vitals-4.jpg' %}' />
{% endblock %}